importing libraries
loads the raw text
splits into chunks
creates document embeddings for chunks
stores embeddings in vector database

In [1]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

C:\Users\scorpious\AppData\Local\Temp\ipykernel_14180\3129460803.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import TextLoader

loading the book dataset

In [2]:
import pandas as pd
books = pd.read_csv("books_with_emotions.csv")

  Export descriptions to a text file as langchain doesnot work with pandas

In [3]:
books["tagged_description"].to_csv(
    "tagged_description.txt",    index=False,
    header=False
)

Loading and splitting  the text file into documents

In [4]:
raw_documents = TextLoader("tagged_description.txt", encoding="latin-1").load()
text_splitter = CharacterTextSplitter(chunk_size=2000, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 2016, which is longer than the specified 2000
Created a chunk of size 2012, which is longer than the specified 2000
Created a chunk of size 2834, which is longer than the specified 2000
Created a chunk of size 2510, which is longer than the specified 2000
Created a chunk of size 2014, which is longer than the specified 2000
Created a chunk of size 2291, which is longer than the specified 2000
Created a chunk of size 2616, which is longer than the specified 2000
Created a chunk of size 2046, which is longer than the specified 2000
Created a chunk of size 2762, which is longer than the specified 2000
Created a chunk of size 2005, which is longer than the specified 2000
Created a chunk of size 2155, which is longer than the specified 2000
Created a chunk of size 2209, which is longer than the specified 2000
Created a chunk of size 2877, which is longer than the specified 2000
Created a chunk of size 2400, which is longer than the specified 2000
Created a chunk of size 2122, which is longer than the specified 2000
Created a chunk of size 2198, which is longer than the specified 2000
Created a chunk of size 2174, which is longer than the specified 2000
Created a chunk of size 2729, which is longer than the specified 2000
Created a chunk of size 2456, which is longer than the specified 2000
Created a chunk of size 2451, which is longer than the specified 2000
Created a chunk of size 3170, which is longer than the specified 2000
Created a chunk of size 2034, which is longer than the specified 2000
Created a chunk of size 2033, which is longer than the specified 2000
Created a chunk of size 2942, which is longer than the specified 2000
Created a chunk of size 2148, which is longer than the specified 2000
Created a chunk of size 2490, which is longer than the specified 2000
Created a chunk of size 3784, which is longer than the specified 2000
Created a chunk of size 2702, which is longer than the specified 2000
Created a chunk of size 5836, which is longer than the specified 2000
Created a chunk of size 2075, which is longer than the specified 2000
Created a chunk of size 2004, which is longer than the specified 2000
Created a chunk of size 2122, which is longer than the specified 2000
Created a chunk of size 2299, which is longer than the specified 2000
Created a chunk of size 2073, which is longer than the specified 2000
Created a chunk of size 2035, which is longer than the specified 2000
Created a chunk of size 2046, which is longer than the specified 2000
Created a chunk of size 2378, which is longer than the specified 2000
Created a chunk of size 2374, which is longer than the specified 2000
Created a chunk of size 2356, which is longer than the specified 2000
Created a chunk of size 2011, which is longer than the specified 2000
Created a chunk of size 2334, which is longer than the specified 2000
Created a chunk of size 2946, which is longer than the specified 2000
Created a chunk of size 3243, which is longer than the specified 2000
Created a chunk of size 2780, which is longer than the specified 2000
Created a chunk of size 2089, which is longer than the specified 2000
Created a chunk of size 2018, which is longer than the specified 2000
Created a chunk of size 2713, which is longer than the specified 2000
Created a chunk of size 2278, which is longer than the specified 2000
Created a chunk of size 2107, which is longer than the specified 2000
Created a chunk of size 2016, which is longer than the specified 2000
Created a chunk of size 2069, which is longer than the specified 2000
Created a chunk of size 2857, which is longer than the specified 2000
Created a chunk of size 2869, which is longer than the specified 2000
Created a chunk of size 2347, which is longer than the specified 2000
Created a chunk of size 2453, which is longer than the specified 2000
Created a chunk of size 2149, which is longer than the specified 2000
Created a chunk of size 2742, which is longer than the specified 2000
Created a chunk of size 3948, which is longer than the specified 2000

 Building  the vector database

In [8]:
import torch
from langchain_huggingface import HuggingFaceEmbeddings

db_books = Chroma.from_documents(
    documents,
    embedding=HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2"),
    persist_directory="chroma_db",      # ← save to disk
    collection_name="books"             # ← name it "books"
)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [7]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k=10)
docs

[Document(id='05de3a7e-a03e-4d69-962e-2fbe7739b1b1', metadata={'source': 'tagged_description.txt'}, page_content='"9780064404419 ""Culled from 69 stories collected in a [1930s] WPA project, [these 20] tales are organized into sections with themes like \'Tricksters\' or \'Virtues and Vices,\' each with a thoughtful introduction placing the individual stories in the context of feelings and background of the original tellers. Yep\'s telling is vigorous, often poetic, imbued with earthy humor and realism touched with fatalism. A handsomely designed collection."" â\x80\x94K. Notable Children\'s Books of 1989 (ALA) The USA Through Children\'s Books 1990 (ALA) 1989 Boston Globeâ\x80\x93Horn Book Award for Nonfiction 1990 Fanfare Honor List (The Horn Book) 1989 Children\'s Editors\' Choices (BL) Notable 1989 Children\'s Trade Books in Social Studies (NCSS/CBC) Children\'s Books of 1989 (Library of Congress) 1989 Children\'s Books (NY Public Library) ""The Best Books"" 1989 (Parents Magazine)"\n"9780064404891 In 1867, Otter travels from Three Willows Village in China to California -- the Land of the Golden Mountain. There he will join his father and uncle. In spite of the presence of family, Otter is a stranger among the other Chinese in this new land. And where he expected to see a land of goldfields, he sees only vast, cold whiteness. But Otter\'s dream is to learn all he can, take the technology back to the Middle Kingdom, and free China from the Manchu invaders. Otter and the others board a machine that will change his life -- a train for which he would open the Dragon\'s Gate."\n"9780064405447 Betsy marries Joe, her high school sweetheart, and they have all the problems of young newlyweds, in a sixtieth anniversary edition of a beloved story which includes a new biographical section and a new forward. Original."\n"9780064405454 In January 1914, with an unsuccessful college experience and a broken romance with Joe behind her, twenty-one-year-old Betsy, traveling alone for the first time, determines to enjoy every moment of her long trip around Europe."'),
 Document(id='c83589eb-80f2-4766-a119-845e784dbfcd', metadata={'source': 'tagged_description.txt'}, page_content='"9780064402453 â\x80\x98Racso, a brash and boastful little rodent, is making his way to Thorn Valley, determined to learn how to read and write and become a hero. His bragging and lies get him off to a bad start, but a crisis gives him the opportunity to prove his mettle. A worthy successor [to Mrs. Frisby and the Rats of NIMH, a Newbery Medal winner by the author\'s father].\' \'BL. 1986 Children\'s Editors\' Choices (BL) Children\'s Choices for 1987 (IRA/CBC) Notable 1986 Childrens\' Trade Books in Social Studies (NCSS/CBC) 1986 Children\'s Books (NY Public Library) Best Science Fiction/Fantasy 1986 (VOYA)"\n"9780064403368 Twelve-year-old Casey is waiting for the day that Barney, her father, hits it big -- \'cause when that horse comes in, he tells her, it\'s the penthouse suite. But then hr ends up in the hospital, and Casey is sent to Chinatown to live with her grandmother, Paw-Paw. Now the waiting seems longer than ever. Casey feels lost in Chinatown. She\'s not prepared for the Chinese school, the noisy crowds, missing her father. But Paw-Paw tells her about the mother Casey never knew, and about her family\'s owl charm and her true Chinese name. And Casey at last begins to understand that this -- Paw-Paw\'s Chinatown home, her parents\' home -- is her home,too."\n"9780064403870 When Margaret and her younger brother, Artie, get lost in the woods on a family camping trip, they are rescued by rats -- the superintelligent rats of NIMH. Taken into the rat\'s community, the children are safe for the time being. But winter is coming. Margaret and Artie have to get back home. And when they do, they must protect the rats who have helped them. Everything depends on their silence... but it\'s hard to evade questions forever. Children\'s Choices for 1991 (IRA/CBC)VOYA\'s Best Science Fiction, Fantasy, and Horror 1990Parenting Honorable Mention, Reading Magic Award"'),
 Document(id='791fa8a6-2550-4090-9c39-a5e1b5f48bc5', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."\n"9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."\n"9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."\n"9780786808717 A very special puddle sets Violet the mouse off on her latest nature discovery. It is through this puddle that Violet observes the effect rain has on the world around her. A Mylar puddle on the last page offers children a chance to see their reflection in a puddle, just like Violet!"'),
 Document(id='6162b0d6-31bb-4ef9-ab75-b8083efb6016', metadata={'source': 'tagged_description.txt'}, page_content='"9780007151240 It should be the most natural thing in the world. But in Tony Parsons\' latest bestseller, three couples discover that Mother Nature can be one hell of a bitch."\n"9780007151677 Gipsy S Acre Was A Truly Beautiful Upland Site With Views Out To Sea And In Michael Rogers It Stirred A Child-Like Fantasy. There, Among The Dark Fir Trees, He Planned To Build A House, Find A Wonderful Girl And Live Happily Ever After, Yet, As He Left The Village, A Shadow Of Menace Hung Over The Land. For This Was The Place Where Accidents Happened. Perhaps Michael Should Have Heeded The Locals Warnings: There S No Luck For Them As Meddles With Gipsy S Acre ."\n"9780007153589 \'The Harper\'s Essay\' is reprinted in this volume alongside personal essays and painstaking, often funny reportage. Although his subjects range widely, each piece wrestles with the erosion of civic life and private dignity, and the hidden persistence of loneliness in postmodern America."\n"9780007154845 A mysterious stranger appears at a New Year\'s Eve party, becoming the enigmatic sleuthing sidekick to the snobbish Mr Satterthwaite... So far, it had been a typical New Year\'s Eve house party. But Mr Satterthwaite - a keen observer of human nature - sensed that the real drama of the evening was yet to unfold. So it proved when a mysterious stranger arrived after midnight. Who was this Mr Quin? And why did his presence have such a pronounced effect on Eleanor Portal, the woman with the dyed-black hair?"'),
 Document(id='60c1927e-b415-4591-a6bf-877c0fb30174', metadata={'source': 'tagged_description.txt'}, page_content='"9780671631987 With more than half a million copies in print, Teach Your Child to Read in 100 Easy Lessons is the definitive guide to giving your child the reading skills needed now for a better chance at tomorrow, while bringing you and your child closer together. Is your child halfway through first grade and still unable to read? Is your preschooler bored with coloring and ready for reading? Do you want to help your child read, but are afraid youâ\x80\x99ll do something wrong? Teach Your Child to Read in 100 Easy Lessons is a complete, step-by-step program that shows patents simply and clearly how to teach their children to read. Twenty minutes a day is all you need, and within 100 teaching days your child will be reading on a solid second-grade reading level. Itâ\x80\x99s a sensible, easy-to-follow, and enjoyable way to help your child gain the essential skills of reading. Everything you need is hereâ\x80\x94no paste, no scissors, no flash cards, no complicated directionsâ\x80\x94just you and your child learning together. One hundred lessons, fully illustrated and color-coded for clarity, give your child the basic and more advanced skills needed to become a good reader."\n"9780671646196 Nancy Harding uses her storytelling gifts to depict a young woman who would defy every tradition of her male-dominated society--and triumph! Set against the ancient world of the Scythian tribes of 513 B.C., Wind Child is a passionate, exhilarating, unforgettable tale."\n"9780671662349 The reminiscences of Miep Gies, the woman who hid the Frank family in Amsterdam during the Second World War, presents a vivid story of life under Nazi occupation."\n"9780671685638 Questions arise concerning the connections between a strangely detached young girl\'s captivity in a seedy Florida motel, a death that occurs at a party for a visiting actress, and a young California instructor\'s obsession with one of his students"'),
 Document(id='914a7099-a1b7-4d3e-b384-e31a238fd394', metadata={'source': 'tagged_description.txt'}, page_content='"9780618446872 The author recounts his odyssey down the length of Africa, from Cairo to South Africa, describing the bad food, many delays, discomforts, and dangers of his trip, along with the people and places of the real Africa."\n"9780618471164 The Earth and Its Peoples Brief Edition is a compact presentation of world history with a comparative approach and a global, balanced perspective. The themes of ""Environment and Technology"" and ""Diversity and Dominance"" unite the regions of the world. The Earth and Its Peoples Brief Edition offers a high level of scholarship with a supportive, student-friendly format."\n"9780618477906 On Christmas eve, a young boy joins some other children on a magical train ride to the North Pole, in an adaptation of the new movie being released this holiday season. Original."\n"9780618477944 A memoir done in the form of a graphic novel by a cult favorite comic artist offers a darkly funny family portrait that details her relationship with her father--a funeral home director, high school English teacher, and closeted homosexual."'),
 Document(id='fdce903c-3b9a-41b8-9875-fc2f8388cda4', metadata={'source': 'tagged_description.txt'}, page_content='"9780064406307 \'Like Cushman\'s 1995 Newbery Honor Book, Catherine, Called Birdy, this novel is about a strong young woman in medieval England who finds her own way home. This is a world, like Chaucer\'s, that\'s . . . dangerous, primitive and raucous. From the first page you\'re caught by the spirit of the homeless, nameless waif, somewhere around 12 years old. She gets the village midwife to take her in, befriends a cat, names herself Alyce, and learns something about delivering babies. When she fails, she runs away, but she picks herself up again and returns to work and independence.\' --ALA Booklist (starred review). \'. . .A fascinating view of a far distant time.\' -- The Horn Book (starred review)"\n"9780064406925 The Little House books tell the story of a little pioneer girl and her family as they traveled by covered wagon across the Midwest. Laura Ingalls Wilder\'s classic books, illustrated with Garth Williams\' timeless artwork, have been cherished by millions of readers ever since they were first published over sixty years ago. This My First Little House Book introduces Almanzo Wilder, the young boy from Farmer Boy who would one day marry Laura Ingalls. In Winter on the Farm, Almanzo goes through his afternoon barn chores, and then sits down to eat a hearty farm supper with his family. In this first book about Almanzo, young readers are able to share in the warmth and joy of another Little House family and celebrate new Little House adventures. Winter on the Farm is the first in an ongoing series about Lauraâ\x80\x99s beloved farmer boy."\n"9780064407144 With the arrival of her new governess, Miss Crow, Martha begins to see that her work is quite important and soon realizes she could learn a great deal from her if she only took the time to get to know her. Simultaneous."'),
 Document(id='124ca355-1a05-470a-8b60-ec6744c9aaf8', metadata={'source': 'tagged_description.txt'}, page_content='9780762427321 Hawking\'s revolutionary look at the scientific discoveries that changed people\'s perceptions of the world now comes complete with color photographs and illustrations depicting theoretical models of the planets and their orbits.\n"9780763619312 When a third grade classmate gets her picture in the paper for winning a spelling bee, Judy is determined to find a way to become famous herself."\n"9780763620875 When Judy Moody gets serious about protecting the environment, her little brother Stink thinks she is overdoing it, but she manages to inspire her third grade class to undertake an award-winning, environment-saving project. Reprint."\n"9780763621643 As a page in his uncle\'s castle in thirteenth-century England, eleven-year-old Tobias records in his journal his experiences learning how to hunt, play games of skill, and behave in noble society."\n"9780763625894 Edward Tulane, a cold-hearted and proud toy rabbit, loves only himself until he is separated from the little girl who adores him and travels across the country, acquiring new owners and listening to their hopes, dreams, and histories. Jr Lib Guild. Teacher\'s Guide available. 300,000 first printing."\n"9780763626150 Judy is excited about becoming a doctor, especially when Class 3T starts a new unit on the human body, but she learns more about being a patient when she catches tonsillitis from her little brother, Stink. Reprint. 75,000 first printing."\n"9780763628000 After learning about the American Revolution on a family trip to Boston, Massachusetts, Judy Moody makes her own Declaration of Independence and tries to prove that she is responsible enough to have more freedoms, such as a higher allowance and her own bathroom. Reprint."\n"9780763628109 When twelve-year-old Daniel Cook and his sister, Beatrice, spend the summer at a special school run by their parents\' eccentric former tutor, they are introduced to the secret study of dragonology and find themselves caught up in an evil plot."'),
 Document(id='cd7215cd-dbf0-4d20-b898-df836a9c35bc', metadata={'source': 'tagged_description.txt'}, page_content='"9780067575208 First published more than three decades ago, this reissue of Rachel Carson\'s award-winning classic brings her unique vision to a new generation of readers. Stunning new photographs by Nick Kelsh beautifully complement Carson\'s intimate account of adventures with her young nephew, Roger, as they enjoy walks along the rocky coast of Maine and through dense forests and open fields, observing wildlife, strange plants, moonlight and storm clouds, and listening to the ""living music"" of insects in the underbrush. ""If a child is to keep alive his inborn sense of wonder."" Writes Carson, ""he needs the companionship of at least one adult who can share it, rediscovering with him the joy, excitement and mystery of the world we live in."" The Sense of Wonder is a refreshing antidote to indifference and a guide to capturing the simple power of discovery that Carson views as essential to life. In her insightful new introduction, Linda Lear remembers Rachel Carson\'s groundbreaking achievements in the context of the legendary environmentalist\'s personal commitment to introducing young and old to the miracles of nature. Kelsh\'s lush photographs inspire sensual, tactile reactions: masses of leaves floating in a puddle are just waiting to be scooped up and examined more closely. An image of a narrow path through the trees evokes the earthy scent of the woods after a summer rain. Close-ups of mosses and miniature lichen fantasy-lands will spark innocent\'as well as more jaded\'imaginations. Like a curious child studying things underfoot and within reach, Kelsh\'s camera is drawn to patterns in nature that too often elude hurried adults\'a stand of beech trees in the springtime, patches of melting snow and the ripples from a pebble tossed into a slow-moving stream. The Sense of Wonder is a timeless volume that will be passed on from children to grandchildren, as treasured as the memory of an early-morning walk when the song of a whippoorwill was heard as if for the first time."'),
 Document(id='ef927b3d-4e8f-41f1-b1cf-8bf8d6741443', metadata={'source': 'tagged_description.txt'}, page_content='9780064405478 A small town shortly after the turn of the century provides the background for this account of Betsy\'s third year at Deep Valley High. Reissue.\n"9780064405713 Increasingly alienated from his widowed father, Vernon joins his friends in ridiculing the neighborhood outcasts\'Maxine, an alcoholic prone to outrageous behavior, and Ronald, her retarded son. But when a social service agency tries to put Ronald into a special home, Vernon fights against the move. 1994 Newbery Honor Book Notable Children\'s Books of 1994 (ALA) 1994 Best Books for Young Adults (ALA) 1994 Young Adult Editors\' Choices (BL) 1994 Books for the Teen Age (NY Public Library) Young Adult Choices for 1995 (IRA)"\n"9780064405850 The land was theirs, but so were its hardships Strawberries -- big, ripe, and juicy. Ten-year-old Birdie Boyer can hardly wait to start picking them. But her family has just moved to the Florida backwoods, and they havenâ\x80²t even begun their planting. "";Donâ\x80²t count your biddies â\x80²fore theyâ\x80²re hatched, gal young un!""; her father tells her. Making the new farm prosper is not easy. There is heat to suffer through, and droughts, and cold snaps. And, perhaps most worrisome of all for the Boyers, there are rowdy neighbors, just itching to start a feud."\n"9780064405959 When seven Siberian snow spiders, frozen during the Ice Age, defrost and escape en route to Harvard for analysis, they wreak havoc on a small New England town, disrupting the school Halloween pageant with hilarious results. An ALA Notable Children\'s Book. Reissue."')]

 Matching  a result back to the books table

In [8]:
books[books["isbn13"] == int(docs[0].page_content.strip('"').split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
407,9780064404419,0064404412,The Rainbow People,Laurence Yep,Juvenile Fiction,http://books.google.com/books/content?id=5AHwq...,"""Culled from 69 stories collected in a [1930s]...",1992.0,3.75,208.0,202.0,The Rainbow People:,"9780064404419 ""Culled from 69 stories collecte..."

 final recommendation function

In [9]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k=50)

    books_list = []
    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [7]:
retrieve_semantic_recommendations("A book about fairy tale ")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise,neutral
56,9780007137336,0007137338,Lirael,Garth Nix,Fantasy fiction,http://books.google.com/books/content?id=sDzU8...,When a dangerous necromancer threatens to unle...,2004.0,4.30,527.0,1339.0,9780007137336 When a dangerous necromancer thr...,Nonfiction,0.064134,0.104007,0.957042,0.040564,0.942740,0.111690,0.078766
146,9780060556501,0060556501,"The Lion, the Witch and the Wardrobe (picture ...",C. S. Lewis,Juvenile Fiction,http://books.google.com/books/content?id=FlSpp...,Narnia: A magical land full of wonder and exci...,2004.0,4.19,48.0,5012.0,9780060556501 Narnia: A magical land full of w...,Children's Fiction,0.500388,0.146838,0.247717,0.863717,0.944420,0.494298,0.621472
216,9780060760823,0060760826,A Couple of April Fools,Gregory Maguire,Juvenile Fiction,http://books.google.com/books/content?id=qW4cv...,"At a Vermont elementary school, April Fools' D...",2005.0,3.50,240.0,3.0,"9780060760823 At a Vermont elementary school, ...",Children's Fiction,0.064134,0.601675,0.319988,0.040564,0.549477,0.111690,0.078766
340,9780060987527,0060987529,Confessions of an Ugly Stepsister,Gregory Maguire,Fiction,http://books.google.com/books/content?id=R7lwa...,Is this new land a place where magics really h...,2000.0,3.52,372.0,53017.0,9780060987527 Is this new land a place where m...,Fiction,0.477070,0.712513,0.823898,0.270591,0.781858,0.308516,0.429871
378,9780061139376,0061139378,Coraline,Neil Gaiman,Fiction,http://books.google.com/books/content?id=pXlAY...,In Coraline's family's new flat there's a lock...,2006.0,4.05,162.0,377685.0,9780061139376 In Coraline's family's new flat ...,Fiction,0.393250,0.179143,0.938569,0.378467,0.874423,0.111690,0.488982
440,9780066238500,0066238501,The Chronicles of Narnia (adult),C. S. Lewis,Fiction,http://books.google.com/books/content?id=3VGkK...,"Journeys to the end of the world, fantastic cr...",2001.0,4.26,767.0,425445.0,9780066238500 Journeys to the end of the world...,Fiction,0.064134,0.104007,0.051363,0.487125,0.951270,0.111690,0.130764
558,9780140071788,0140071784,Roald Dahl's Book of Ghost Stories,Roald Dahl,"Ghost stories, American",http://books.google.com/books/content?id=zGt6R...,Who better to investigate the literary spirit ...,1985.0,3.69,249.0,2403.0,9780140071788 Who better to investigate the li...,Fiction,0.064134,0.104007,0.773546,0.040564,0.549477,0.253176,0.078766
646,9780140367430,0140367438,The Enchanted Castle,E. Nesbit,Juvenile Fiction,http://books.google.com/books/content?id=75V6x...,"E. Nesbit's classic story of how Gerald, Cathy...",2004.0,3.85,291.0,6124.0,9780140367430 E. Nesbit's classic story of how...,Children's Fiction,0.090869,0.165256,0.749953,0.120340,0.549477,0.111690,0.768096
648,9780140430363,0140430369,Three Gothic Novels,Horace Walpole;William Beckford;Mary Shelley,Fiction,http://books.google.com/books/content?id=ZjI_D...,"Walpole's The Castle of Otranto, Beckford's Va...",1968.0,3.70,505.0,290.0,"9780140430363 Walpole's The Castle of Otranto,...",Fiction,0.064134,0.104007,0.982916,0.698616,0.877477,0.111690,0.163506
682,9780140445503,0140445501,Gargantua and Pantagruel,Francois Rabelais;Michael Andrew Screech,Biography & Autobiography,http://books.google.com/books/content?id=fWwts...,The dazzling and exuberant moral stories of Ra...,2006.0,3.71,1041.0,11605.0,9780140445503 The dazzling and exuberant moral...,Nonfiction,0.118239,0.645261,0.051363,0.961089,0.549477,0.111690,0.078766
713,9780140714555,0140714553,A Midsummer Night's Dream,William Shakespeare,Drama,http://books.google.com/books/content?id=P0Ceh...,"Two pairs of star-crossed lovers, a feuding pa...",2000.0,3.94,144.0,984.0,9780140714555 Two pairs of star-crossed lovers...,Fiction,0.064134,0.104007,0.051363,0.223559,0.583579,0.111690,0.088222
730,9780141014081,0141014083,Complete Maus,Art Spiegelman,Children of Holocaust survivors,http://books.google.com/books/content?id=rBj-n...,Combined here are Maus I: A Survivor's Tale an...,2003.0,4.55,296.0,100212.0,9780141014081 Combined here are Maus I: A Surv...,Nonfiction,0.064134,0.104007,0.946176,0.073686,0.877911,0.111690,0.078766
873,9780143039860,0143039865,Sometimes a Great Notion,Ken Kesey,Fiction,http://books.google.com/books/content?id=WToh-...,The magnificent second novel from the legendar...,1964.0,4.21,715.0,557.0,9780143039860 The magnificent second novel fro...,Fiction,0.891767,0.104007,0.051363,0.491093,0.860675,0.111690,0.375920
952,9780192807267,0192807269,Candide and Other Stories,Voltaire,Fiction,http://books.google.com/books/content?id=zxJGB...,Candide is the most famous of Voltaire's 'phil...,2006.0,3.94,301.0,3336.0,9780192807267 Candide is the most famous of Vo...,Fiction,0.114236,0.066910,0.849088,0.557936,0.889838,0.253268,0.173095
956,9780192823311,0192823310,Four Gothic Novels,Horace Walpole;William Beckford;Matthew Lewis;...,NaN,http://books.google.com/books/content?id=dADYA...,"Macabre and melodramatic, set in haunted castl...",1994.0,3.95,624.0,143.0,"9780192823311 Macabre and melodramatic, set in...",Fiction,0.064134,0.926358,0.983829,0.431481,0.549477,0.111690,0.106745
960,9780192832436,0192832433,Exemplary Stories,Miguel de Cervantes Saavedra;Lesley Lipson,Fiction,http://books.google.com/books/content?id=62hVB...,Even more popular in their day than Don Quixot...,1998.0,3.73,368.0,777.0,9780192832436 Even more popular in their day t...,Fiction,0.064134,0.104007,0.116454,0.960260,0.549477,0.111690,0.802859
1016,9780198711551,0198711557,The Canterbury Tales,Helen Cooper,Literary Criticism,http://books.google.com/books/content?id=2KNzQ...,"Since its first publication in 1989, Helen Coo...",1996.0,4.01,456.0,83.0,9780198711551 Since its first publication in 1...,Nonfiction,0.064134,0.104007,0.051363,0.156141,0.942389,0.111690,0.078766
1278,9780312869595,0312869592,Jack of Kinrowan,Charles de Lint,Fiction,http://books.google.com/books/content?id=FcODd...,The two stories of Jacky Rowan are combined in...,1999.0,4.11,412.0,3648.0,9780312869595 The two stories of Jacky Rowan a...,Fiction,0.064134,0.104007,0.708378,0.040564,0.950357,0.111690,0.322443
1462,9780345417961,0345417968,The 158-Pound Marriage,John Irving,Fiction,http://books.google.com/books/content?id=MBIVg...,The darker vision and sexual ambiguities of th...,1997.0,3.24,176.0,11124.0,9780345417961 The darker vision and sexual amb...,Fiction,0.299554,0.221329,0.051363,0.827566,0.770712,0.111690,0.078766
1808,9780385319270,0385319274,There's No Such Place as Far Away,Richard Bach,Fiction,http://books.google.com/books/content?id=ZtATw...,Inspired by correspondence between Bach and a ...,1998.0,3.93,48.0,2665.0,9780385319270 Inspired by correspondence betwe...,Fiction,0.015775,0.007262,0.007388,0.267151,0.646731,0.013459,0.042234
2136,9780439682589,0439682584,Harry Potter,J. K. Rowling,Juvenile Fiction,http://books.google.com/books/content?id=DAAAA...,The first five years of Harry Potter magic are...,2004.0,4.78,2690.0,38872.0,9780439682589 The first five years of Harry Po...,Children's Fiction,0.064134,0.104007,0.051363,0.067914,0.883493,0.111690,0.161523
2144,9780439793957,0439793955,The Case of the Snowboarding Superstar,James Preller,Juvenile Fiction,http://books.google.com/books/content?id=n0Z2G...,When Jigsaw Jones goes to Vermont with his fam...,2006.0,3.97,80.0,117.0,9780439793957 When Jigsaw Jones goes to Vermon...,Children's Fiction,0.064134,0.104007,0.051363,0.040564,0.549477,0.630307,0.078766
2224,9780441005833,0441005837,Rose Daughter,Robin McKinley,Juvenile Fiction,http://books.google.com/books/content?id=RtiQP...,The winner of the Newbery Award for The Hero a...,1998.0,3.77,304.0,16756.0,9780441005833 The winner of the Newbery Award ...,Children's Fiction,0.064134,0.104007,0.944353,0.040564,0.950357,0.111690,0.081668
2238,9780441014439,0441014437,Harrowing the Dragon,Patricia A. McKillip,Fiction,http://books.google.com/books/content?id=bzZ8D...,"Spanning a quarter of a century, an anthology ...",2006.0,3.94,308.0,1567.0,"9780441014439 Spanning a quarter of a century,...",Fiction,0.023973,0.028355,0.025466,0.052876,0.847774,0.030455,0.041677
2410,9780451457592,0451457595,The River's Gift,Mercedes Lackey,Fiction,http://books.google.com/books/content?id=qLonv...,Fifteen-year-old Ariella spends her days in th...,1999.0,3.88,128.0,1029.0,9780451457592 Fifteen-year-old Ariella spends ...,Fiction,0.064134,0.104007,0.929467,0.040564,0.549477,0.111690,0.078766
2633,9780552154284,0552154288,Hogfather,Terry Pratchett,Christmas,http://books.google.com/books/content?id=uiP3l...,Susan had never hung up a stocking . She'd nev...,2006.0,4.24,432.0,56929.0,9780552154284 Susan had never hung up a stocki...,Nonfiction,0.235731,0.300591,0.752370,0.040564,0.953557,0.282585,0.194375
2635,9780552548632,0552548634,Beauty,Robin McKinley,Fairy tales,http://books.google.com/books/content?id=mEY96...,"When the family business collapses, Beauty and...",2004.0,4.05,271.0,251.0,9780552548632 When the family business collaps...,Fiction,0.064134,0.338704,0.576328,0.811433,0.549477,0.910886,0.166629
2882,9780600601166,0600601161,The New Hite Report,Shere Hite,Sexual behavior surveys,http://books.google.com/books/content?id=7gzFQ...,This new report includes previously unpublishe...,2000.0,3.76,667.0,22.0,9780600601166 This new report includes previou...,Nonfiction,0.064134,0.218063,0.051363,0.235828,0.919456,0.111690,0.115477
3242,9780694524754,0694524751,The Chronicles of Narnia CD Box Set,C. S. Lewis,Juvenile Fiction,NaN,Listen to all seven stories in C. S. Lewis's c...,2004.0,4.26,31.0,198.0,9780694524754 Listen to all seven stories in C...,Children's Fiction,0.097501,0.104007,0.122382,0.582165,0.945227,0.208502,0.487818
3270,9780736805995,0736805990,"The Girlhood Diary of Louisa May Alcott, 1843-...",Louisa May Alcott,Juvenile Nonfiction,http://books.google.com/books/content?id=_dP35...,Excerpts from the girlhood diary of Louisa May...,2001.0,3.87,32.0,26.0,9780736805995 Excerpts from the girlhood diary...,Children's Nonfiction,0.064134,0.104168,0.051363,0.175410,0.937971,0.111690,0.078766
3543,9780756401818,075640181X,The War of the Flowers,Tad Williams,Fiction,http://books.google.com/books/content?id=Yofu6...,"When his music career becomes stagnant, thirty...",2004.0,3.87,828.0,7401.0,9780756401818 When his music career becomes st...,Fiction,0.064134,0.104007,0.984400,0.040564,0.950357,0.111690,0.078766
3659,9780765348210,0765348217,The Family Trade,Charles Stross,Fiction,http://books.google.com/books/content?id=VuTCi...,Believing she has found a career-making story ...,2005.0,3.52,308.0,4561.0,9780765348210 Believing she has found a career...,Fiction,0.064134,0.104007,0.359574,0.040564,0.950357,0.111690,0.609207
3667,9780765357663,0765357666,Hidden Talents,David Lubar,Juvenile Fiction,http://books.google.com/books/content?id=wgEFP...,When thirteen-year-old Martin Anderson arrives...,2007.0,3.93,240.0,2333.0,9780765357663 When thirteen-year-old Martin An...,Children's Fiction,0.064134,0.104007,0.051363,0.371783,0.950357,0.111690,0.972556
3838,9780802789471,0802789471,Once Upon a Cool Motorcycle Dude,Kevin O'Malley,Juvenile Fiction,http://books.google.com/books/content?id=9-fBH...,Once upon a time there was ... a princess who ...,2005.0,4.08,32.0,1730.0,9780802789471 Once upon a time there was ... a...,Children's Fiction,0.200959,0.941329,0.391731,0.836217,0.833871,0.293257,0.530746
4064,9780822218739,0822218739,An Adult Evening of Shel Silverstein,Shel Silverstein,Drama,http://books.google.com/books/content?id=gUnMD...,THE STORIES: Welcome to the darkly comic world...,2003.0,4.02,72.0,195.0,9780822218739 THE STORIES: Welcome to the dark...,Fiction,0.007784,0.006411,0.962584,0.508643,0.384683,0.005595,0.089574
4262,9780940450738,0940450739,"Collected tales, sketches, speeches, and essay...",Mark Twain,"Humorous stories, American",http://books.google.com/books/content?id=hhzGw...,This with its companion volume is the most com...,1992.0,4.39,1050.0,199.0,9780940450738 This with its companion volume i...,Fiction,0.064134,0.104007,0.051363,0.713611,0.549477,0.111690,0.078766
4293,9780974514055,0974514055,Programming Ruby,David Thomas,Computers,http://books.google.com/books/content?id=wX9jQ...,A tutorial and reference to the object-oriente...,2004.0,4.04,828.0,1525.0,9780974514055 A tutorial and reference to the ...,Nonfiction,0.007042,0.011359,0.014233,0.047894,0.963389,0.020174,0.027937
4483,9781416502043,1416502041,The Voyage of the Jerle Shannara Trilogy,Terry Brooks,Fantasy,http://books.google.com/books/content?id=jqVsA...,When the body of a half-drowned elf is found f...,2004.0,4.26,1260.0,84.0,9781416502043 When the body of a half-drowned ...,Fiction,0.416537,0.640165,0.975743,0.307788,0.871304,0.363081,0.182557
4559,9781551112237,155111223X,Alice's Adventures in Wonderland,Lewis Carroll,Juvenile Fiction,http://books.google.com/books/content?id=HJ8Wg...,"First published in 1865, Alice's Adventures in...",2000.0,4.01,356.0,72.0,"9781551112237 First published in 1865, Alice's...",Children's Fiction,0.064134,0.104007,0.201197,0.763002,0.951433,0.111690,0.691648
4635,9781565047082,1565047087,Changeling Storytellers Guide,Mark Hunter;Nancy Schultz-Yetter;Steve Kenson;...,Games,http://books.google.com/books/content?id=3sMLA...,"The gates to Arcadia, the original paradise, a...",1998.0,3.37,139.0,27.0,"9781565047082 The gates to Arcadia, the origin...",Nonfiction,0.114938,0.728054,0.149556,0.830439,0.939859,0.776592,0.868735
4654,9781567430288,1567430287,Zora neale Hurston,Henry L. Gates,Literary Criticism,http://books.google.com/books/content?id=BfhnQ...,Zora Neale Hurston(1891 -- 1960) Of the variou...,2000.0,4.20,238.0,24.0,9781567430288 Zora Neale Hurston(1891 -- 1960)...,Nonfiction,0.158104,0.387028,0.197793,0.450432,0.860241,0.111690,0.116527
4717,9781577314035,1577314034,Myths of Light,Joseph Campbell,Philosophy,http://books.google.com/books/content?id=OWdqt...,This previously unpublished title shows Campbe...,2003.0,4.42,224.0,330.0,9781577314035 This previously unpublished titl...,Nonfiction,0.064134,0.104007,0.051363,0.438826,0.927367,0.111690,0.465306
4809,9781586857721,158685772X,It's Easy Being Green,Crissy Trask,House & Home,http://books.google.com/books/content?id=82_En...,Provides a comprehensive guide to adopting gre...,2006.0,3.53,168.0,326.0,9781586857721 Provides a comprehensive guide t...,Nonfiction,0.064134,0.104007,0.051363,0.102935,0.936846,0.111690,0.078766
4811,9781587150883,1587150883,The Well at the World's End,William Morris;Lin Carter,Fiction,http://books.google.com/books/content?id=ASCIv...,The Well at the Worlds End By William Morris T...,2000.0,3.77,332.0,251.0,9781587150883 The Well at the Worlds End By Wi...,Fiction,0.064134,0.566684,0.173852,0.984901,0.956839,0.191052,0.147712
4882,9781593076672,1593076673,Facts in the Case of the Departure of Miss Fin...,Neil Gaiman;Michael Zulli,Comics & Graphic Novels,http://books.google.com/books/content?id=U_vsw...,"Come, come and hear of the strange and terribl...",2008.0,3.55,51.0,1934.0,"9781593076672 Come, come and hear of the stran...",Fiction,0.064134,0.104007,0.948149,0.581398,0.871755,0.111690,0.236563
4899,9781593854461,1593854463,Teaching Reading Comprehension to Students wit...,Janette K. Klingner;Sharon Vaughn;Alison Boardman,Education,http://books.google.com/books/content?id=NfLfn...,A ChoiceOutstanding Academic Title! A highly p...,2007.0,3.77,178.0,22.0,9781593854461 A ChoiceOutstanding Academic Tit...,Children's Nonfiction,0.064134,0.104007,0.051363,0.574818,0.957861,0.111690,0.078766
4923,9781595820631,1595820639,Tale of Genji,Yoshitaka Amano,Art,http://books.google.com/books/content?id=1tgAw...,Yoshitaka Amano has been praised around the wo...,2006.0,4.06,81.0,462.0,9781595820631 Yoshitaka Amano has been praised...,Nonfiction,0.064134,0.129483,0.051363,0.596346,0.715662,0.111690,0.135859
5094,9781885865243,1885865244,Through a Brazen Mirror,Delia Sherman,Fiction,http://books.google.com/books/content?id=ajlbA...,Through a Brazen Mirror is the third book in T...,1999.0,3.38,100.0,116.0,9781885865243 Through a Brazen Mirror is the t...,Fiction,0.347284,0.204335,0.307270,0.614794,0.942909,0.417159,0.100624
5189,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,9788122200850 This book is the story of a youn...,Fiction,0.541743,0.226292,0.305920,0.040564,0.594006,0.111690,0.078766
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,9788173031014 This book tells the tale of a ma...,Nonfiction,0.064134,0.114383,0.051363,0.400262,0.883199,0.111690,0.227765